Used CastIronJs approach to scrape the Free Rotation.
rhots/automation pull request #9
Opened 2017-01-10 21:19 UTC by kalebhermes

2017-01-10 21:34 UTC, kalebhermes commented
Basically all I did was take the code you wrote to scrape the listing page, and slotted it into what I already had. I figured this would take the least amount of time, as I can just re-enable the posting code that's already written.

2017-01-11 05:26 UTC, yuna9 requested changes
Minor comment.

2017-01-11 05:26 UTC, justinkim commented on bin/get_official_heroes.py
> +    heroes = [(h['name'], h['slug']) for h in heroes if h['inFreeHeroRotation'] == True]
Can we instead print all heroes, also printing their free rotation availability?

`heroes = [(h['name'], h['slug'], h['inFreeHeroRotation']) for h in heroes]`

2017-01-11 05:26 UTC, justinkim commented on heroes-sidebar-master/freeRotation.py
> +	    browser = webdriver.PhantomJS()
Eventually, I'd like to pull this portion of code that fetches the data from the website into a separate module. For now, it can live here.

2017-01-12 14:53 UTC, yuna9 approved these changes

2017-01-12 14:53 UTC, kalebhermes commented
I've made the requested change.

2017-01-12 14:53 UTC, merged